import React,{useEffect,useId,useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,ArrowDownToLine,Check,Plus,Trash2,Layers,PackageCheck,Scissors,RefreshCw,Sprout,Ruler,Box,AlertTriangle,Info,ChevronRight,ShieldCheck} from 'lucide-react';
import {makeParts,packParts} from './packing.js';
import {createDesign,pathFromPolygons} from './geometry.js';
import {inspectFeatures,measureKerf} from './preflight.js';
import {placementPaths,buildJobZip} from './job-export.js';
import {download} from './export.js';
import {standDimensions,standSTL} from './stand.js';
import StandPreview from './StandPreview.jsx';

const machines={falcon2:{name:'Falcon2 40W',width:400,height:415},a1:{name:'Falcon A1',width:305,height:381},custom:{name:'自定义工作区',width:400,height:400}};
const sampleStocks=()=>[{id:'offcut',name:'上次剩下的窄条',width:300,height:80,count:4,reclaimed:true},{id:'sheet',name:'常用整板',width:300,height:400,count:4,reclaimed:false}];
const defaultSettings={machine:'falcon2',bedWidth:400,bedHeight:415,quantity:1,mode:'rings',margin:4,gap:3,stocks:sampleStocks(),demo:true,minWidth:2.4,actualThickness:3,clearance:.6};
function initialSettings(design){try{const s=JSON.parse(localStorage.getItem('memory-workshop-settings'));if(s){packParts(makeParts(design.size,s.quantity,s.mode),s.stocks,s);standDimensions(s.actualThickness,s.clearance);if(Number.isFinite(s.minWidth)&&s.minWidth>=.5&&s.minWidth<=5)return {...defaultSettings,...s,nominalMaterial:design.material,actualThickness:s.nominalMaterial===design.material?s.actualThickness:design.thickness};}}catch{}return {...defaultSettings,nominalMaterial:design.material,actualThickness:design.thickness};}
const pct=n=>`${(n*100).toFixed(1)}%`;
function readMeasurement(material){try{const d=JSON.parse(localStorage.getItem(`memory-workshop-calibration-${material}`));if(d&&typeof d.outer==='string'&&typeof d.hole==='string')return d;}catch{}return {outer:'',hole:''};}

function SheetArt({design,sheet,selected,onSelect,interactive=true}){
  const gridId=`board-grid-${useId().replace(/:/g,'')}`;
  if(!sheet)return <div className="empty-sheet">当前库存无法放入任何零件。<br/>请核对设备工作区与板材尺寸。</div>;
  return <svg className="sheet-art" viewBox={`-5 -5 ${sheet.width+10} ${sheet.height+10}`} role="img" aria-label={`${sheet.name}排版图，${sheet.placements.length}个零件`}>
    <defs><pattern id={gridId} width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#d7d8c8" strokeWidth=".35"/></pattern></defs>
    <rect width={sheet.width} height={sheet.height} rx="2" fill="#ece6d4" stroke="#acaa91" strokeWidth=".6"/>
    <rect width={sheet.width} height={sheet.height} fill={`url(#${gridId})`}/>
    {sheet.placements.map(p=>{const a=placementPaths(design,p);return <g key={p.id} className="sheet-part" role={interactive?'button':undefined} tabIndex={interactive?0:undefined} aria-label={interactive?p.name:undefined} onKeyDown={e=>{if(interactive&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onSelect(p.id);}}} onClick={()=>interactive&&onSelect(p.id)}>
      <rect x={p.x} y={p.y} width={p.width} height={p.height} fill="transparent"/>
      <g transform={a.transform}><path d={a.cut} fill={p.kind==='strip'?'#c3934b':p.kind==='spacer'?'#a8b795':'#5e8c78'} fillOpacity={selected===p.id?.95:.68} stroke={selected===p.id?'#f7a443':'#365e4f'} strokeWidth={selected===p.id?1.1:.5} fillRule="evenodd"/>{a.engrave.map((d,i)=><path key={i} d={d} transform={`scale(${a.scale})`} fill="none" stroke="#2d4e49" strokeWidth=".7"/>)}</g>
      {p.kind!=='strip'&&<text x={p.x+5} y={p.y+8} fill="#203f35" fontSize="4.5">{p.unit} / {p.kind==='layer'?`L${p.layerId+1}`:'间隔框'}</text>}
    </g>;})}
  </svg>;
}
function Comparison({name,result,active,onClick,subtitle}){return <button className={`comparison-card ${active?'active':''}`} onClick={onClick}><span>{name}{active&&<Check size={15}/>}</span><strong>{!result?'暂时无法排版':result.unplaced.length?`缺 ${result.unplaced.length} 个零件`:'可以排下全部零件'}</strong><small>{result?`新板 ${result.stats.newSheetCount} 张 · 余料 ${result.stats.reclaimedSheetCount} 张`: '请检查库存输入'}</small><em>{subtitle}</em></button>;}

export default function Production({design,source,onSizeChange,reinforcement,onReinforce,onBack}){
  const [settings,setSettings]=useState(()=>initialSettings(design));
  const [boardView,setBoardView]=useState('single');
  const [sheetIndex,setSheetIndex]=useState(0),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[planning,setPlanning]=useState(null),[exporting,setExporting]=useState(false);
  const [riskLayer,setRiskLayer]=useState(()=>inspectFeatures(design,2.4).layers.sort((a,b)=>b.area-a.area)[0].id),[outer,setOuter]=useState(()=>readMeasurement(design.material).outer),[hole,setHole]=useState(()=>readMeasurement(design.material).hole);
  const update=(key,value)=>{setSettings(s=>({...s,[key]:value}));setMessage('');setPlanning(null);};
  useEffect(()=>{try{localStorage.setItem('memory-workshop-settings',JSON.stringify(settings));}catch{}},[settings]);
  useEffect(()=>{try{localStorage.setItem(`memory-workshop-calibration-${design.material}`,JSON.stringify({outer,hole}));}catch{}},[outer,hole,design.material]);
  useEffect(()=>{setMessage('');},[design,source,settings,outer,hole]);
  const result=useMemo(()=>{try{const rings=packParts(makeParts(design.size,settings.quantity,'rings'),settings.stocks,settings);const strips=packParts(makeParts(design.size,settings.quantity,'strips'),settings.stocks,settings);return {rings,strips,job:settings.mode==='rings'?rings:strips};}catch(e){return {error:e.message};}},[design.size,settings.quantity,settings.mode,settings.stocks,settings.bedWidth,settings.bedHeight,settings.margin,settings.gap]);
  const job=result.job,sheet=job?.sheets[Math.min(sheetIndex,job.sheets.length-1)];
  const risk=useMemo(()=>inspectFeatures(design,settings.minWidth),[design,settings.minWidth]);
  const baseRisk=useMemo(()=>reinforcement?inspectFeatures(createDesign(design.plan,{size:design.size,material:design.thickness===1.5?'card':'wood'}),settings.minWidth):risk,[design,settings.minWidth,reinforcement,risk]);
  const layerRisk=risk.layers.find(l=>l.id===riskLayer)||risk.layers[0],layer=design.layers[layerRisk.id];
  const calibration=outer!==''&&hole!==''?measureKerf(+outer,+hole):null;
  let stand,standError;try{stand=standDimensions(settings.actualThickness,settings.clearance);}catch(e){standError=e.message;}
  const selectedPart=sheet?.placements.find(p=>p.id===selected);
  function editStock(i,key,value){setSettings(s=>({...s,demo:false,stocks:s.stocks.map((v,j)=>j===i?{...v,[key]:value}:v)}));setPlanning(null);}
  function recommend(){
    if(result.error){setMessage(result.error);return;}
    const candidates=[];
    for(const size of [220,180,140].filter(s=>s<=design.size))for(const mode of ['rings','strips']){
      const p=packParts(makeParts(size,settings.quantity,mode),settings.stocks,settings);
      candidates.push({size,mode,result:p});
    }
    const feasible=candidates.filter(c=>!c.result.unplaced.length).sort((a,b)=>b.size-a.size||a.result.stats.newSheetCount-b.result.stats.newSheetCount||a.result.stats.sheetArea-b.result.stats.sheetArea);
    if(!feasible.length){setPlanning({failed:true,text:`比较了 ${candidates.length} 个尺寸与结构方案，库存仍不足。请增加合适的板材或减少成品数量。`,checked:candidates.length,candidates});return;}
    applyCandidate(feasible[0],candidates,design.size);
  }
  function applyCandidate(best,candidates,previous,manual=false){
    onSizeChange(best.size);setSettings(s=>({...s,mode:best.mode}));setSheetIndex(0);setSelected('');setBoardView('all');
    setPlanning({failed:false,checked:candidates.length,candidates,manual,chosen:`${best.size}-${best.mode}`,text:`${previous===best.size?'保留':'调整为'} ${best.size/10} cm，采用${best.mode==='strips'?'拼条间隔框':'整框'}。使用 ${best.result.stats.newSheetCount} 张新板、${best.result.stats.reclaimedSheetCount} 张余料，${best.result.stats.totalCount} 个零件全部排下。`,previous});
  }
  async function exportJob(){setExporting(true);try{download(await buildJobZip(design,source,job,settings,risk,calibration),`拾光工坊-${design.plan.title.replace(/[\\/:*?"<>|]/g,'')}-生产包.zip`);setMessage('生产包已下载，先打开里面的生产交接单。');}catch(e){setMessage(e.message);}finally{setExporting(false);}}
  return <div className="production-page">
    <section className="production-intro"><div><span className="eyebrow"><span className="mini-line"/> MAKE MORE WITH WHAT YOU HAVE</span><h1>先看看手边，<em>再决定怎么做。</em></h1><p>让余料重新成为礼物。把一件设计，变成有限库存里可执行的制作方案。</p></div><div className="work-order"><svg className="work-order-preview" viewBox="-5 -5 210 210" aria-label="当前作品缩略图">{[...design.layers].reverse().map(l=><path key={l.id} d={l.path} fill={l.color} fillRule="evenodd"/>)}</svg><div className="work-order-info"><span>当前作品 / {source==='kiro'?'Kiro AI 方案':'示例方案'}</span><strong>{design.plan.title}</strong><small>{design.size/10} × {design.size/10} cm · {settings.quantity} 件</small><button onClick={onBack}>回到故事设计 <ArrowUpRight size={13}/></button></div></div></section>
    <div className="production-layout">
      <aside className="production-settings">
        <section><div className="section-heading"><span className="step-number">01</span><h2>这次，做多少？</h2></div><div className="production-pair"><label>成品尺寸<select value={design.size} onChange={e=>{onSizeChange(+e.target.value);setPlanning(null);}} aria-label="生产成品尺寸">{[140,180,220].map(v=><option key={v} value={v}>{v/10} × {v/10} cm</option>)}</select></label><label>成品数量<select value={settings.quantity} onChange={e=>update('quantity',+e.target.value)} aria-label="成品数量">{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} 件</option>)}</select></label></div><p className="field-help">同款批量。每件 6 层图案、5 个间隔框。</p></section>
        <section><div className="section-heading"><span className="step-number">02</span><h2>设备与手边材料</h2></div><label className="production-field">激光工作区<select value={settings.machine} aria-label="激光设备" onChange={e=>{const m=machines[e.target.value];setSettings(s=>({...s,machine:e.target.value,bedWidth:m.width,bedHeight:m.height}));setPlanning(null);}}>{Object.entries(machines).map(([k,m])=><option key={k} value={k}>{m.name}{k==='custom'?'':` · ${m.width} × ${m.height}`}</option>)}</select></label>
          {settings.machine==='custom'&&<div className="production-pair"><label>工作区宽 mm<input type="number" value={settings.bedWidth} onChange={e=>update('bedWidth',+e.target.value)} min="20" max="1000"/></label><label>工作区高 mm<input type="number" value={settings.bedHeight} onChange={e=>update('bedHeight',+e.target.value)} min="20" max="1000"/></label></div>}
          <div className="stock-heading"><span>可用库存 · {settings.demo?'演示数据':'手工录入'}</span><button onClick={()=>{setSettings(s=>({...s,stocks:sampleStocks(),demo:true}));setPlanning(null);}}>载入余料示例</button></div>
          <p className="field-help">所有板材按当前 {design.material} 计算；余料需同材同厚、平整可切。</p>
          <div className="stock-list">{settings.stocks.map((s,i)=><div className={`stock-row ${s.reclaimed?'reclaimed':''}`} key={s.id}><div className="stock-row-title"><label><input type="checkbox" checked={s.reclaimed} aria-label={`库存${i+1}为余料`} onChange={e=>editStock(i,'reclaimed',e.target.checked)}/><span>{s.reclaimed?'余料优先':'整板库存'}</span></label><button aria-label={`删除库存${i+1}`} onClick={()=>{setSettings(v=>({...v,demo:false,stocks:v.stocks.filter((_,j)=>j!==i)}));setPlanning(null);}}><Trash2 size={13}/></button></div><div className="stock-dimensions"><label>宽 mm<input type="number" aria-label={`库存${i+1}宽`} value={s.width} min="20" max="1000" onChange={e=>editStock(i,'width',+e.target.value)}/></label><i>×</i><label>高 mm<input type="number" aria-label={`库存${i+1}高`} value={s.height} min="20" max="1000" onChange={e=>editStock(i,'height',+e.target.value)}/></label><label>张数<input type="number" aria-label={`库存${i+1}数量`} value={s.count} min="0" max="40" onChange={e=>editStock(i,'count',+e.target.value)}/></label></div></div>)}</div>
          <button className="add-stock" disabled={settings.stocks.length>=8} onClick={()=>{setSettings(s=>({...s,demo:false,stocks:[...s.stocks,{id:`stock-${Date.now()}`,name:'手工录入板材',width:300,height:200,count:1,reclaimed:true}]}));setPlanning(null);}}><Plus size={14}/> 添加一份库存</button>
          <div className="production-pair compact"><label>板边留白 mm<input type="number" aria-label="板边留白" min="0" max="20" value={settings.margin} onChange={e=>update('margin',+e.target.value)}/></label><label>零件间距 mm<input type="number" aria-label="零件间距" min="1" max="15" value={settings.gap} onChange={e=>update('gap',+e.target.value)}/></label></div>
          {result.error&&<div className="production-alert" role="alert">{result.error}</div>}
          <button className="primary-button full-width recommend" onClick={recommend}><RefreshCw size={16}/> 按库存找可行方案 <ArrowRight size={16}/></button><p className="field-help centered">比较尺寸与结构，保留尽可能大的作品。<br/>本机计算，不额外消耗 AI 额度。</p>
        </section>
      </aside>
      <section className="production-main">
        <div className="production-summary"><div><span className="eyebrow">FROM DESIGN TO A WORKABLE PLAN</span><h2>同一段回忆，<span>换一种做法。</span></h2></div><span className={`job-status ${job?.unplaced.length||!job?'pending':'ready'}`}>{job&&!job.unplaced.length?<><Check size={14}/> 零件已全部排入</>:<><AlertTriangle size={14}/> 当前方案放不下</>}</span></div>
        <div className="comparison-grid"><Comparison name="原方案 · 整框" result={result.rings} active={settings.mode==='rings'} onClick={()=>update('mode','rings')} subtitle="装配简单，需整块板材"/><Comparison name="省料方案 · 拼条" result={result.strips} active={settings.mode==='strips'} onClick={()=>update('mode','strips')} subtitle="窄余料也能用，增加胶粘定位步骤"/></div>
        {planning&&<div className={`planning-result ${planning.failed?'failed':''}`} role="status"><span><RefreshCw size={16}/> 本次求解</span><p>{planning.text}</p><small>{planning.manual?'已按你的选择切换方案；库存与零件数量已重新对应。':`比较 ${planning.checked} 个候选 · 保留最大可行尺寸，再比较新板数与板面占用。`}</small>
          <details className="candidate-details"><summary>查看 {planning.checked} 个方案的对比依据</summary><div className="candidate-table-wrap"><table><caption className="sr-only">当前库存下各尺寸与结构的排版结果</caption><thead><tr><th>尺寸 / 结构</th><th>新板 / 余料</th><th>结果</th></tr></thead><tbody>{planning.candidates.map(c=>{const chosen=planning.chosen===`${c.size}-${c.mode}`;return <tr key={`${c.size}-${c.mode}`} className={chosen?'chosen':''}><td>{c.size/10} cm · {c.mode==='strips'?'拼条':'整框'}</td><td>{c.result.stats.newSheetCount} / {c.result.stats.reclaimedSheetCount} 张</td><td>{c.result.unplaced.length?<span className="candidate-missing">缺 {c.result.unplaced.length} 件</span>:chosen?<span className="candidate-current"><Check size={12}/> 当前采用</span>:<button onClick={()=>applyCandidate(c,planning.candidates,planning.previous,true)}>采用此方案 <ArrowUpRight size={11}/></button>}</td></tr>;})}</tbody></table></div><small>缺件行中的板数为已放入的部分；完整交付以零件全部排下为准。</small></details>
        </div>}
        <div className="board-workspace"><div className="board-toolbar"><div><span className="board-dot"/> {boardView==='all'?`全部 ${job?.sheets.length??0} 张板材`:sheet?`${sheet.reclaimed?'余料':'新板'} / ${sheet.width} × ${sheet.height} mm`:'等待可用板材'}</div><div className="board-view-toggle" aria-label="排版查看方式"><button aria-pressed={boardView==='single'} onClick={()=>setBoardView('single')}>单张细看</button><button aria-pressed={boardView==='all'} onClick={()=>setBoardView('all')}>全部板材</button></div></div>
          {boardView==='all'&&job?.sheets.length?<div className="board-overview" aria-label="全部板材总览">{job.sheets.map((s,i)=><button key={s.id} className={`sheet-thumbnail ${s.reclaimed?'reclaimed':''}`} aria-label={`查看第${i+1}张${s.reclaimed?'余料':'新板'}，${s.placements.length}个零件`} onClick={()=>{setSheetIndex(i);setSelected('');setBoardView('single');}}><span><b>{String(i+1).padStart(2,'0')}</b>{s.reclaimed?<><Sprout size={12}/>余料</>:<><Layers size={12}/>新板</>}</span><SheetArt design={design} sheet={s} interactive={false}/><strong>{s.width} × {s.height} mm</strong><small>{s.placements.length} 个零件 · 点击细看 <ArrowUpRight size={10}/></small></button>)}</div>:<div className="board-canvas"><SheetArt design={design} sheet={sheet} selected={selected} onSelect={setSelected}/><div className="board-legend"><span><i/> 图案层</span><span><i/> 间隔材料</span><small>红色加工线在导出文件中</small></div></div>}
          <div className="board-tabs" aria-label="板材分页">{job?.sheets.map((s,i)=><button key={s.id} className={s===sheet&&boardView==='single'?'active':''} onClick={()=>{setSheetIndex(i);setSelected('');setBoardView('single');}}>{s.reclaimed?<Sprout size={12}/>:<Layers size={12}/>} {i+1}</button>)}</div><div className="part-detail">{boardView==='all'?'按实际库存逐张展示，点击板材查看零件位置。':selectedPart?`${selectedPart.name} · ${selectedPart.width} × ${selectedPart.height} mm · 位置 (${selectedPart.x}, ${selectedPart.y})${selectedPart.rotated?' · 旋转90°':''}`:'图纸与当前设计共用轮廓；不会为排版偷偷缩放或删除零件。'}</div></div>
        <div className="production-metrics"><div><span>新板用量</span><strong>{job?.stats.newSheetCount??'—'}<small> 张</small></strong></div><div><span>重用余料</span><strong>{job?.stats.reclaimedSheetCount??'—'}<small> 张</small></strong></div><div><span>已安排零件</span><strong>{job?`${job.stats.placedCount}/${job.stats.totalCount}`:'—'}</strong></div><div><span>矩形占地率</span><strong>{job?pct(job.stats.utilization):'—'}</strong></div></div>
        {!!job?.unplaced.length&&<div className="production-alert"><AlertTriangle size={16}/><p>还有 {job.unplaced.length} 个零件未安排。可尝试拼条结构、缩小成品或补充库存；未完成时不能导出生产包。</p></div>}
        {!!job?.stats.rejectedStocks.length&&<div className="production-alert"><Info size={16}/><p>{job.stats.rejectedStocks.map(s=>`${s.name}：${s.reason}`).join('；')}。不会把超出设备的板材自动裁小。</p></div>}
        <p className="planning-footnote">矩形启发式排版，优先用余料；不保证全局最优。占地率按矩形包络计算，不是净材料利用率。<a href="https://www.crealityfalcon.com/collections/laser-engravers" target="_blank" rel="noreferrer">工作区尺寸来源 <ArrowUpRight size={10}/></a></p>
      </section>
    </div>
    <section className="production-tools-heading"><span className="eyebrow">BEFORE THE FIRST CUT</span><h2>少一次返工，<em>多一份把握。</em></h2><p>找出细节风险，记录实测数据，让文件接得上真实工具。</p></section>
    <div className="production-tools">
      <section className="tool-panel risk-panel"><div className="tool-heading"><ShieldCheck size={19}/><h3>细节体检与加固</h3><span>几何估计</span></div><p>高亮可能过细的尖端、连接与小孔，帮助选择试切位置。</p><label className="production-field">期望保留的细节宽度 <b>{settings.minWidth} mm</b><input type="range" min=".5" max="5" step=".1" value={settings.minWidth} aria-label="细节宽度阈值" onChange={e=>update('minWidth',+e.target.value)}/></label><div className="risk-preview"><svg viewBox="-5 -5 210 210" aria-label="细节风险高亮图"><path d={layer.path} fill="#c8d8c5" fillRule="evenodd"/>{layerRisk.riskAreas.map((p,i)=><path key={i} d={pathFromPolygons([p])} fill="#cc5638"/>) }{layerRisk.smallHoles.map((r,i)=><path key={`h${i}`} d={pathFromPolygons([[r]])} fill="#e4a33c" stroke="#b06527" strokeWidth=".7"/>)}</svg><div><strong>{risk.regions}</strong><span>处需留意</span><small>红：细节<br/>橙：小孔</small></div></div><select aria-label="风险检查图层" value={riskLayer} onChange={e=>setRiskLayer(+e.target.value)}>{risk.layers.map(l=><option value={l.id} key={l.id}>第{l.id+1}层 · {l.name} · {l.riskAreas.length+l.smallHoles.length}处</option>)}</select><div className="reinforce-control"><span>轮廓加固</span><div>{[0,.4,.8,1.2].map(v=><button key={v} aria-pressed={reinforcement===v} onClick={()=>onReinforce(v)}>{v?`+${v} mm`:'原图'}</button>)}</div></div><p className="risk-delta">疑似薄弱区域 {baseRisk.riskArea.toFixed(1)} → <b>{risk.riskArea.toFixed(1)} mm²</b></p><small className="tool-note">加固实际修改预览与导出轮廓，也会缩小或封闭小孔。提示有近似，不能代替实材试切。</small></section>
      <section className="tool-panel calibration-panel"><div className="tool-heading"><Ruler size={19}/><h3>把试切变成记录</h3></div><p>30 mm 外片与 10 mm 方孔，做一次双向测量，记录这批材料的切缝。</p><div className="calibration-drawing"><svg viewBox="0 0 200 150" aria-hidden="true"><rect x="46" y="25" width="108" height="108" fill="#e8dbc0" stroke="#a78752"/><rect x="82" y="61" width="36" height="36" fill="#faf8f1" stroke="#a78752"/><path d="M46 15H154 M46 10V20 M154 10V20" stroke="#91a08a"/><text x="100" y="8" textAnchor="middle">30 mm</text><text x="100" y="112" textAnchor="middle">孔 10 mm</text></svg></div><div className="production-pair"><label>外片实测 mm<input type="number" aria-label="外片实测" placeholder="例 29.80" step=".01" value={outer} onChange={e=>setOuter(e.target.value)}/></label><label>方孔实测 mm<input type="number" aria-label="方孔实测" placeholder="例 10.20" step=".01" value={hole} onChange={e=>setHole(e.target.value)}/></label></div><div className={`kerf-result ${calibration?.valid&&!calibration.consistent?'warn':''}`}>{calibration?.valid?<><span>切缝估计</span><strong>{calibration.kerf.toFixed(3)} <small>mm</small></strong><p>{calibration.consistent?'两次测量一致，可作为该材料批次的参考。':'两次测量差异偏大，请检查测量方法或重新试切。'}</p></>:<p>{calibration?.error||'还没有实测数据。没有设备时可以留空。'}</p>}</div><small className="tool-note">实测记录随生产包保存；未自动施加切缝补偿。</small></section>
      <section className="tool-panel stand-panel"><div className="tool-heading"><Box size={19}/><h3>一张图，两种制造</h3><span>STL</span></div><p>激光制作故事层，3D 打印展示底座。槽宽随叠层厚度变化。</p>{stand?<StandPreview thickness={settings.actualThickness} clearance={settings.clearance}/>:<div className="stand-model">{standError}</div>}<div className="production-pair"><label>实测板厚 mm<input type="number" aria-label="实测板厚" min=".8" max="5" step=".1" value={settings.actualThickness} onChange={e=>update('actualThickness',+e.target.value)}/></label><label>总装配余量 mm<input type="number" aria-label="装配余量" min=".2" max="2" step=".1" value={settings.clearance} onChange={e=>update('clearance',+e.target.value)}/></label></div><div className="stand-equation">11 × {settings.actualThickness} + {settings.clearance} = <b>{stand?.slot??'—'} mm</b><span>槽宽包含 6 层图案与 5 层间隔，不含额外外箱。</span></div><button className="secondary-button full-width" disabled={!stand} onClick={()=>download(new Blob([standSTL(settings.actualThickness,settings.clearance)],{type:'model/stl'}),'拾光工坊-展示底座.stl')}><ArrowDownToLine size={15}/> 下载底座 STL</button><small className="tool-note">可导入 Creality Print。模型网格已检查，打印、装配与稳定性仍需实物验证。</small></section>
    </div>
    <section className="production-delivery"><div><PackageCheck size={28}/><div><h3>带走一份可以交接的生产包。</h3><p>整板 SVG · 零件定位表 · 底座 STL · 实测记录 · 装配与交接说明</p></div></div><button className="primary-button" disabled={!job||!!job.unplaced.length||!stand||!design.validation.pass||exporting} onClick={exportJob}><ArrowDownToLine size={17}/>{exporting?'正在打包…':'下载完整生产包'}<ArrowUpRight size={15}/></button></section>
    {message&&<div className="production-message" role="status">{message}</div>}
    <p className="production-limits">当前为本机原型；没有连接、控制或认证任何实体设备。库存与测量来自手工输入。设计与排版经过软件检查，实体效果需要试做确认。</p>
  </div>;
}
